<?php
/**
 * Generated by tools/export-wp-theme.js - do not edit.
 * Source: src/layout.js
 */
?></main>

<footer class="site-footer">
  <div class="wrap">
    <div class="footer__signup">
      <div>
        <h2>Method notes, straight to your inbox</h2>
        <p>
          A short monthly note on analytical method, handling and storage, written by the team that
          runs our testing programme. No promotional mail, and one click to stop it.
        </p>
      </div>
      <a class="btn btn--accent btn--lg" href="/contact/?topic=newsletter">Sign up now</a>
    </div>

    <div class="footer__grid">
      <div class="footer__brand">
        <!-- Dark ground, so the supplied full-colour lockup is used as-is. -->
        <a class="logo logo--full" href="/">
          <img src="/wp-content/themes/pph-child/assets/img/brand/logo-ondark.png" width="210" height="213" alt="Purely Peptides Hub - Innovation, Quality, Research.">
        </a>
        <address class="footer__addr">
          Address line 1<br>City, State ZIP<br>United States<br>
          <a href="mailto:support@purelypeptideshub.com">support@purelypeptideshub.com</a><br>
          <a href="tel:+10000000000">+1 (000) 000-0000</a>
        </address>
        <div class="footer__social">
          <a href="https://www.linkedin.com/" rel="noopener" aria-label="LinkedIn"><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M4.98 3.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5ZM3 9h4v12H3zM9 9h3.8v1.7h.05c.53-.95 1.83-1.95 3.77-1.95 4.03 0 4.78 2.5 4.78 5.75V21h-4v-5.6c0-1.34-.03-3.06-1.9-3.06-1.9 0-2.2 1.45-2.2 2.96V21H9z"/></svg></a><a href="https://x.com/" rel="noopener" aria-label="X"><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M17.5 3h3.2l-7 8 8.2 10h-6.4l-5-6.1L4.7 21H1.5l7.5-8.6L1.2 3h6.6l4.5 5.6zm-1.1 16h1.8L7.7 4.9H5.8z"/></svg></a><a href="https://www.youtube.com/" rel="noopener" aria-label="YouTube"><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M21.6 7.2a2.5 2.5 0 0 0-1.76-1.77C18.27 5 12 5 12 5s-6.27 0-7.84.43A2.5 2.5 0 0 0 2.4 7.2C2 8.78 2 12 2 12s0 3.22.4 4.8a2.5 2.5 0 0 0 1.76 1.77C5.73 19 12 19 12 19s6.27 0 7.84-.43a2.5 2.5 0 0 0 1.76-1.77C22 15.22 22 12 22 12s0-3.22-.4-4.8ZM10 15.2V8.8l5.2 3.2z"/></svg></a><a href="https://www.facebook.com/" rel="noopener" aria-label="Facebook"><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M22 12a10 10 0 1 0-11.56 9.88v-6.99H7.9V12h2.54V9.8c0-2.5 1.5-3.89 3.77-3.89 1.1 0 2.24.2 2.24.2v2.46h-1.26c-1.24 0-1.63.77-1.63 1.56V12h2.78l-.45 2.89h-2.33v6.99A10 10 0 0 0 22 12Z"/></svg></a>
        </div>
      </div>
      <nav aria-labelledby="f-products">
        <h2 id="f-products">Products</h2>
        <button class="footer__acc-toggle" type="button" data-facc aria-expanded="false">Products<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14" class="chev"><path d="m6 9 6 6 6-6"/></svg></button>
        <ul class="footer__list"><li><a href="/products/">All products</a></li><li><a href="/products/category/metabolic-research/">Metabolic Research</a></li><li><a href="/products/category/growth-factor-research/">Growth Factor Research</a></li><li><a href="/products/?sort=newest">New materials</a></li></ul>
      </nav><nav aria-labelledby="f-quality">
        <h2 id="f-quality">Quality</h2>
        <button class="footer__acc-toggle" type="button" data-facc aria-expanded="false">Quality<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14" class="chev"><path d="m6 9 6 6 6-6"/></svg></button>
        <ul class="footer__list"><li><a href="/certificates/">Certificates</a></li><li><a href="/certificates/">Batch verification</a></li><li><a href="/quality/#testing">Testing</a></li><li><a href="/quality/">Quality process</a></li></ul>
      </nav><nav aria-labelledby="f-research">
        <h2 id="f-research">Research</h2>
        <button class="footer__acc-toggle" type="button" data-facc aria-expanded="false">Research<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14" class="chev"><path d="m6 9 6 6 6-6"/></svg></button>
        <ul class="footer__list"><li><a href="/research/">Research library</a></li><li><a href="/research/?filter=Methods">Technical resources</a></li><li><a href="/applications/">Applications</a></li><li><a href="/faq/">FAQs</a></li></ul>
      </nav><nav aria-labelledby="f-ordering">
        <h2 id="f-ordering">Ordering</h2>
        <button class="footer__acc-toggle" type="button" data-facc aria-expanded="false">Ordering<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14" class="chev"><path d="m6 9 6 6 6-6"/></svg></button>
        <ul class="footer__list"><li><a href="/shipping/">Shipping</a></li><li><a href="/refunds/">Refunds &amp; returns</a></li><li><a href="/wholesale/">Wholesale</a></li><li><a href="<?php echo esc_url( wc_get_account_endpoint_url( 'orders' ) ); ?>">Order tracking</a></li></ul>
      </nav><nav aria-labelledby="f-company">
        <h2 id="f-company">Company</h2>
        <button class="footer__acc-toggle" type="button" data-facc aria-expanded="false">Company<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14" class="chev"><path d="m6 9 6 6 6-6"/></svg></button>
        <ul class="footer__list"><li><a href="/about/">About</a></li><li><a href="/contact/">Contact</a></li><li><a href="/terms/">Terms &amp; conditions</a></li><li><a href="/privacy/">Privacy</a></li><li><a href="/chargebacks/">Chargeback policy</a></li><li><a href="/research-use-policy/">Research use policy</a></li></ul>
      </nav>
    </div>

    <!-- First sentence is the exact wording required by our payment
         processor's research-use-only site rules. Do not reword it. -->
    <p class="footer__disclaimer">
      <strong>All products sold on this website are intended for research and identification purposes only. These products are not intended for human dosing, injection, or ingestion.</strong>
      Materials supplied by Purely Peptides Hub are for laboratory, academic and institutional research by
      qualified professionals. They are not drugs, foods, dietary supplements, cosmetics or medical devices,
      and are not for human or animal consumption, diagnostic use or clinical application. Nothing on this site
      is a claim of therapeutic, performance or health effect. Purchasers are responsible for compliance with all
      applicable laws and institutional requirements governing the handling and disposal of research materials.
    </p>

    <div class="footer__legal">
      <span>© 2026 Purely Peptides Hub. All rights reserved.</span>
      <span class="row" style="gap:20px;flex-wrap:wrap">
        <a href="/terms/">Terms</a><a href="/privacy/">Privacy</a><a href="/shipping/">Shipping</a><a href="/refunds/">Refunds &amp; returns</a><a href="/chargebacks/">Chargebacks</a><a href="/research-use-policy/">Research use policy</a>
      </span>
    </div>
  </div>
</footer>
<div class="mobile-nav" data-mobile-nav data-open="false" role="dialog" aria-modal="true" aria-label="Site menu">
  <div class="mobile-nav__head">
    <span class="logo__name">Purely<span class="logo__name2">Peptides Hub</span></span>
    <button class="iconbtn" type="button" data-mobile-close aria-label="Close menu"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18"/></svg></button>
  </div>
  <div class="mobile-nav__body">
    <form class="searchbar" action="/search/" method="get" role="search" style="margin-bottom:16px">
      <span class="searchbar__icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="M20 20l-3.6-3.6"/></svg></span>
      <label class="visually-hidden" for="m-search">Search</label>
      <input id="m-search" name="q" type="search" placeholder="Search products, CAS, SKU or lot">
    </form>
    
    <div class="mobile-nav__group">
      <button class="mobile-nav__trigger" type="button" data-mnav aria-expanded="false">Products<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14" class="chev"><path d="m6 9 6 6 6-6"/></svg></button>
           <div class="mobile-nav__panel" data-open="false"><div>
             <a href="/products/category/metabolic-research/">Metabolic Research</a><a href="/products/category/growth-factor-research/">Growth Factor Research</a><a href="/products/category/cell-signalling-research/">Cell Signalling Research</a><a href="/products/category/cognitive-research/">Cognitive Research</a><a href="/products/category/melanocortin-research/">Melanocortin Research</a><a href="/products/category/cofactors/">Cofactors &amp; Nucleotides</a><a href="/products/category/blends/">Blends</a><a href="/products/">All products</a>
           </div></div>
    </div>
    
    <div class="mobile-nav__group">
      <button class="mobile-nav__trigger" type="button" data-mnav aria-expanded="false">Research area<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14" class="chev"><path d="m6 9 6 6 6-6"/></svg></button>
           <div class="mobile-nav__panel" data-open="false"><div>
             <a href="/products/?area=Metabolism">Metabolism</a><a href="/products/?area=Endocrine%20Research">Endocrine Research</a><a href="/products/?area=Cell%20Signalling">Cell Signalling</a><a href="/products/?area=Neuroscience">Neuroscience</a><a href="/products/?area=Receptor%20Pharmacology">Receptor Pharmacology</a><a href="/products/?area=Inflammatory%20Research">Inflammatory Research</a><a href="/products/?area=Redox%20%26%20Cofactor">Redox &amp; Cofactor</a>
           </div></div>
    </div>
    
    <div class="mobile-nav__group">
      <button class="mobile-nav__trigger" type="button" data-mnav aria-expanded="false">Quality &amp; testing<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14" class="chev"><path d="m6 9 6 6 6-6"/></svg></button>
           <div class="mobile-nav__panel" data-open="false"><div>
             <a href="/quality/">Quality process</a><a href="/certificates/">Certificate library</a><a href="/quality/#testing">Testing standards</a><a href="/research-use-policy/">Research use policy</a>
           </div></div>
    </div>
    
    <div class="mobile-nav__group">
      <a class="mobile-nav__trigger" href="/research/">Research library<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14"><path d="m9 6 6 6-6 6"/></svg></a>
    </div>
    
    <div class="mobile-nav__group">
      <a class="mobile-nav__trigger" href="/applications/">Applications<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14"><path d="m9 6 6 6-6 6"/></svg></a>
    </div>
    
    <div class="mobile-nav__group">
      <a class="mobile-nav__trigger" href="/wholesale/">Wholesale<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14"><path d="m9 6 6 6-6 6"/></svg></a>
    </div>
    
    <div class="mobile-nav__group">
      <a class="mobile-nav__trigger" href="/contact/">Support<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14"><path d="m9 6 6 6-6 6"/></svg></a>
    </div>
  </div>
  <div class="mobile-nav__foot">
    <a class="btn btn--secondary btn--block" href="<?php echo esc_url( wc_get_page_permalink( 'myaccount' ) ); ?>">Sign in</a>
    <a class="btn btn--primary btn--block" href="/certificates/">Verify a batch</a>
  </div>
</div>

<aside class="cart-drawer" data-cart-drawer data-open="false" role="dialog" aria-modal="true" aria-label="Order summary">
  <div class="cart-drawer__head">
    <h2 style="font-size:var(--t-h4)">Your order <span class="mono muted small" data-cart-countword>(0 items)</span></h2>
    <button class="modal__close" type="button" data-cart-close aria-label="Close order summary"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18"/></svg></button>
  </div>
  <div class="cart-drawer__body">
    <div data-cart-lines></div>

    <div class="empty" data-cart-empty hidden>
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 4h2l2.4 11.2a2 2 0 0 0 2 1.6h7.7a2 2 0 0 0 2-1.6L21 8H6"/><circle cx="10" cy="20" r="1.2"/><circle cx="18" cy="20" r="1.2"/></svg>
      <h3>Your order is empty</h3>
      <p>Materials you add will appear here, with the certificate for the lot that ships.</p>
      <a class="btn btn--secondary" href="/products/">Browse the catalogue</a>
    </div>

    <div class="notice notice--accent" data-cart-docnote hidden style="margin-top:24px">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z"/><path d="M14 3v5h5"/><path d="M9 13h6M9 17h4"/></svg>
      <div>Certificates for every lot in this order are attached and will be available in your account after checkout.</div>
    </div>
  </div>
  <div class="cart-drawer__foot">
    <div class="trow"><span>Subtotal</span><span class="num" data-cart-subtotal>$0.00</span></div>
    <div class="trow"><span>Shipping</span><span class="num muted">Calculated at checkout</span></div>
    <a class="btn btn--primary btn--block btn--lg" href="/checkout/" style="margin-top:12px" data-cart-checkout data-region-gated>Proceed to checkout</a>
    <a class="btn btn--secondary btn--block" href="/cart/" style="margin-top:8px">View full order</a>
  </div>
</aside>

<div class="modal-scrim" data-modal="region" data-open="false" role="dialog" aria-modal="true" aria-labelledby="region-title">
  <div class="modal">
    <div class="modal__head">
      <div>
        <h2 id="region-title" style="font-size:var(--t-h3)">Shipping destination</h2>
        <p class="small muted" style="margin-top:6px">Shipping rates, tax and availability follow the destination state.</p>
      </div>
      <button class="modal__close" type="button" data-modal-close aria-label="Close"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18"/></svg></button>
    </div>
    <div class="modal__body">
      <div class="grid grid-2" style="gap:0 24px">
        <label class="check">
              <input type="radio" name="region" value="MA" data-region-set>
              <span>Massachusetts<span class="check__count">MA</span></span>
            </label><label class="check">
              <input type="radio" name="region" value="TX" data-region-set>
              <span>Texas<span class="check__count">TX</span></span>
            </label><label class="check">
              <input type="radio" name="region" value="FL" data-region-set>
              <span>Florida<span class="check__count">FL</span></span>
            </label><label class="check">
              <input type="radio" name="region" value="IL" data-region-set>
              <span>Illinois<span class="check__count">IL</span></span>
            </label><label class="check">
              <input type="radio" name="region" value="CA" data-region-set>
              <span>California<span class="check__count">Restricted</span></span>
            </label><label class="check">
              <input type="radio" name="region" value="NY" data-region-set>
              <span>New York<span class="check__count">Restricted</span></span>
            </label><label class="check">
              <input type="radio" name="region" value="LA" data-region-set>
              <span>Louisiana<span class="check__count">Restricted</span></span>
            </label><label class="check">
              <input type="radio" name="region" value="WA" data-region-set>
              <span>Washington<span class="check__count">WA</span></span>
            </label>
      </div>
      <div class="notice" style="margin-top:16px">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 7.5v.01"/></svg>
        <div>Three states currently restrict shipment of these materials: <strong>California, New York and Louisiana</strong>. Selecting one of them blocks checkout rather than failing after payment.</div>
      </div>
    </div>
    <div class="modal__foot">
      <button class="btn btn--secondary" type="button" data-modal-close>Cancel</button>
      <button class="btn btn--primary" type="button" data-modal-close>Save region</button>
    </div>
  </div>
</div>

<div class="toast-region" data-toasts aria-live="polite" aria-atomic="false"></div>

<!-- 21+ age and intended-use gate, shown before the site can be used. Our
     payment processor requires a 21+ verification popup ahead of entry, so
     this is a condition of the merchant account, not decoration. It renders
     hidden and is revealed by script so it never blocks a crawler or a
     no-JS reader; it is a declaration of intent, not a security control. -->
<div class="agegate" data-agegate hidden role="dialog" aria-modal="true" aria-labelledby="agegate-title">
  <div class="agegate__card">
    <img class="agegate__mark" src="/wp-content/themes/pph-child/assets/img/brand/mark.png" width="56" height="56" alt="" aria-hidden="true">
    <span class="eyebrow">Before you enter</span>
    <h2 id="agegate-title">You must be 21 or over</h2>
    <p>
      Purely Peptides Hub supplies materials for laboratory, academic and institutional research by
      qualified professionals. Nothing on this site is a drug, food, dietary supplement, cosmetic or
      medical device, and nothing here is for human dosing, injection or ingestion.
    </p>
    <ul class="agegate__list">
      <li><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 6 9 17l-5-5"/></svg>I am <strong>21 years of age or older</strong></li>
      <li><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 6 9 17l-5-5"/></svg>I am purchasing for laboratory research purposes only</li>
      <li><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 6 9 17l-5-5"/></svg>I will not administer these materials to humans or animals</li>
    </ul>
    <div class="agegate__actions">
      <button class="btn btn--primary btn--lg" type="button" data-agegate-accept>I am 21 or over - enter</button>
      <a class="btn btn--secondary btn--lg" href="https://www.google.com/" rel="noopener">I am under 21 - exit</a>
    </div>
    <p class="agegate__fine">
      Your confirmation is stored in this browser so you are not asked again. See our
      <a class="link" href="/research-use-policy/">research use policy</a> and
      <a class="link" href="/terms/">terms</a>.
    </p>
  </div>
</div>
<?php wp_footer(); ?>
</body>
</html>
