<?php
/**
 * Generated by tools/export-wp-theme.js - do not edit.
 * Source: src/layout.js
 */
?><!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script>document.documentElement.classList.add('has-js')</script>
<?php wp_head(); ?>
</head>
<body <?php body_class( 'pph' ); ?>>
<a class="skip-link" href="#main">Skip to main content</a>

<!-- The utility strip sits OUTSIDE the sticky header on purpose. Inside it, the
     header had to shrink on scroll to stay a reasonable size, and shrinking a
     sticky element changes document height, which nudges scrollY, which
     re-crosses the threshold - a visible flicker loop. Out here it just
     scrolls away once, for free, and the header below keeps a constant
     height. -->
<div class="utility">
    <div class="wrap utility__inner">
      <div class="utility__group">
        <button class="utility__note" type="button" data-modal-open="region" style="background:none;border:0;color:inherit;cursor:pointer;font:inherit;">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18"/><path d="M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18Z"/></svg><span>United States - <span data-region-label>MA</span> · USD</span>
        </button>
        <span class="utility__sep utility__group--mobilehide"></span>
        <span class="utility__note utility__group--mobilehide"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M10 3v6.5L4.6 18a2 2 0 0 0 1.7 3h11.4a2 2 0 0 0 1.7-3L14 9.5V3"/><path d="M8.5 3h7M7.5 14h9"/></svg><span>For laboratory research use only</span></span>
      </div>
      <div class="utility__group utility__group--desk">
        <a href="/contact/">Support</a>
        <span class="utility__sep"></span>
        <a href="<?php echo esc_url( wc_get_account_endpoint_url( 'orders' ) ); ?>">Orders</a>
        <span class="utility__sep"></span>
        <a href="<?php echo esc_url( wc_get_page_permalink( 'myaccount' ) ); ?>#wishlist">Wishlist <span class="utility__badge" data-wish-count hidden>0</span></a>
        <span class="utility__sep"></span>
        <a href="<?php echo esc_url( wc_get_page_permalink( 'myaccount' ) ); ?>">Sign in</a>
      </div>
    </div>
  </div>
</div>

<header class="site-header" data-header>
  <div class="wrap masthead">
    <!-- The supplied lockup sets "PURELY" in white, so it disappears on a light
         ground. The mark is used as artwork and the wordmark is set in type,
         which keeps the header legible on paper and crisp at every density.
         The full colour lockup is used on the dark footer, where it works. -->
    <a class="logo" href="/">
      <img class="logo__mark" src="/wp-content/themes/pph-child/assets/img/brand/mark.png" width="40" height="40" alt="" aria-hidden="true">
      <span class="logo__word">
        <span class="logo__name">Purely<span class="logo__name2">Peptides Hub</span></span>
        <span class="logo__sub">Research materials</span>
      </span>
    </a>

    <div class="masthead__search searchwrap">
      <form class="searchbar" action="/search/" method="get" role="search" autocomplete="off">
        <span class="searchbar__icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="M20 20l-3.6-3.6"/></svg></span>
        <label class="visually-hidden" for="site-search">Search products, CAS numbers, SKU or lot number</label>
        <input id="site-search" name="q" type="search" placeholder="Search products, CAS, SKU, articles or lot numbers"
               data-suggest aria-expanded="false" aria-controls="suggest-panel" aria-autocomplete="list" role="combobox">
        <button class="btn btn--primary" type="submit">Search</button>
      </form>
      <div class="suggest" id="suggest-panel" data-open="false" role="listbox" aria-label="Search suggestions"></div>
    </div>

    <div class="masthead__actions">
      <button class="iconbtn mobile-toggle" type="button" data-mobile-open aria-label="Open menu" aria-expanded="false">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18"/></svg><span>Menu</span>
      </button>
      <button class="iconbtn search-toggle" type="button" data-search-open aria-label="Search">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="M20 20l-3.6-3.6"/></svg><span>Search</span>
      </button>
      <a class="iconbtn" href="<?php echo esc_url( wc_get_page_permalink( 'myaccount' ) ); ?>"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 21v-1a5 5 0 0 0-5-5H9a5 5 0 0 0-5 5v1"/><circle cx="12" cy="7" r="4"/></svg><span>Account</span></a>
      <button class="iconbtn" type="button" data-cart-open aria-label="Open your order">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 4h2l2.4 11.2a2 2 0 0 0 2 1.6h7.7a2 2 0 0 0 2-1.6L21 8H6"/><circle cx="10" cy="20" r="1.2"/><circle cx="18" cy="20" r="1.2"/></svg><span>Cart</span><span class="iconbtn__badge" data-cart-count hidden>0</span>
      </button>
    </div>
  </div>

  <nav class="primary-nav" aria-label="Primary">
    <div class="wrap">
      <ul class="primary-nav__list">
        <li>
        <button class="primary-nav__link" type="button" data-mega="products" aria-expanded="false" aria-controls="mega-products">
          Products<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14" class="chev"><path d="m6 9 6 6 6-6"/></svg>
        </button>
      </li><li><a class="primary-nav__link" href="/research/">Research</a></li><li>
        <button class="primary-nav__link" type="button" data-mega="quality" aria-expanded="false" aria-controls="mega-quality">
          Quality &amp; Testing<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" width="14" height="14" class="chev"><path d="m6 9 6 6 6-6"/></svg>
        </button>
      </li><li><a class="primary-nav__link" href="/applications/">Applications</a></li><li><a class="primary-nav__link" href="/wholesale/">Wholesale</a></li><li><a class="primary-nav__link" href="/certificates/">Resources</a></li><li><a class="primary-nav__link" href="/contact/">Support</a></li>
        <li class="primary-nav__right">
          <a class="link-arrow" href="/certificates/"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z"/><path d="M14 3v5h5"/><path d="M9 13h6M9 17h4"/></svg><span>Verify a batch</span></a>
        </li>
      </ul>
    </div>
    
  <div class="mega" id="mega-products" data-open="false" role="region" aria-label="Shop by category">
    <div class="wrap mega__inner">
      
    <div class="mega__col">
      <h3>Shop by category</h3>
      <ul class="mega__list">
        <li><a href="/products/category/metabolic-research/">Metabolic Research<span class="n">7</span></a></li><li><a href="/products/category/growth-factor-research/">Growth Factor Research<span class="n">4</span></a></li><li><a href="/products/category/cell-signalling-research/">Cell Signalling Research<span class="n">5</span></a></li><li><a href="/products/category/cognitive-research/">Cognitive Research<span class="n">2</span></a></li><li><a href="/products/category/melanocortin-research/">Melanocortin Research<span class="n">3</span></a></li><li><a href="/products/category/cofactors/">Cofactors &amp; Nucleotides<span class="n">1</span></a></li><li><a href="/products/category/blends/">Blends<span class="n">3</span></a></li><li><a href="/products/" style="font-weight:600">All products</a></li>
      </ul>
    </div>
    <div class="mega__col">
      <h3>Shop by research area</h3>
      <ul class="mega__list">
        <li><a href="/products/?area=Metabolism">Metabolism</a></li><li><a href="/products/?area=Endocrine%20Research">Endocrine Research</a></li><li><a href="/products/?area=Cell%20Signalling">Cell Signalling</a></li><li><a href="/products/?area=Neuroscience">Neuroscience</a></li><li><a href="/products/?area=Receptor%20Pharmacology">Receptor Pharmacology</a></li><li><a href="/products/?area=Inflammatory%20Research">Inflammatory Research</a></li><li><a href="/products/?area=Redox%20%26%20Cofactor">Redox &amp; Cofactor</a></li><li><a href="/products/">Other areas</a></li>
      </ul>
    </div>
    <div class="mega__col">
      <h3>Quality &amp; documentation</h3>
      <ul class="mega__list">
        <li><a href="/certificates/">Certificates of analysis</a></li><li><a href="/certificates/#verify">Batch verification</a></li><li><a href="/quality/#testing">Testing standards</a></li><li><a href="/quality/">Quality process</a></li><li><a href="/research-use-policy/">Research use policy</a></li>
      </ul>
    </div>
    <div class="mega__col">
      <h3>Featured</h3>
      <ul class="mega__list">
        <li><a href="/products/?sort=newest">New research materials</a></li><li><a href="/products/?sort=featured">Most viewed</a></li><li><a href="/research/">Research library</a></li><li><a href="/wholesale/">Wholesale programme</a></li>
      </ul>
    </div>
      <div class="mega__feature">
        <span class="eyebrow">New</span>
        <h3>Batch verification</h3>
        <p>Enter a lot number to open the analytical documentation issued for that exact production run.</p>
        <a class="btn btn--onDark btn--sm" href="/certificates/">Verify a batch</a>
      </div>
    </div>
  </div>
    
  <div class="mega" id="mega-quality" data-open="false" role="region" aria-label="How we test">
    <div class="wrap mega__inner">
      
    <div class="mega__col">
      <h3>How we test</h3>
      <ul class="mega__list">
        <li><a href="/quality/">Quality process</a></li><li><a href="/quality/#testing">Testing standards</a></li><li><a href="/quality/#methods">Analytical methods</a></li><li><a href="/quality/#labs">Third-party laboratories</a></li>
      </ul>
    </div>
    <div class="mega__col">
      <h3>Documentation</h3>
      <ul class="mega__list">
        <li><a href="/certificates/">Certificate library</a></li><li><a href="/certificates/">Search by lot number</a></li><li><a href="/research/what-a-certificate-of-analysis-contains/">How to read a COA</a></li><li><a href="/research/reading-an-hplc-purity-result/">Reading an HPLC result</a></li>
      </ul>
    </div>
    <div class="mega__col">
      <h3>Policies</h3>
      <ul class="mega__list">
        <li><a href="/research-use-policy/">Research use policy</a></li><li><a href="/shipping/">Shipping &amp; handling</a></li><li><a href="/refunds/">Refunds &amp; returns</a></li><li><a href="/chargebacks/">Chargeback policy</a></li><li><a href="/terms/">Terms &amp; conditions</a></li>
      </ul>
    </div>
    <div class="mega__col">
      <h3>Support</h3>
      <ul class="mega__list">
        <li><a href="/contact/?topic=documentation">Documentation support</a></li><li><a href="/contact/?topic=product">Product specifications</a></li><li><a href="/faq/">Frequently asked questions</a></li><li><a href="/contact/">Contact the team</a></li>
      </ul>
    </div>
      <div class="mega__feature">
        <span class="eyebrow">Method</span>
        <h3>What we test for</h3>
        <p>Every eligible lot is assessed by reversed-phase HPLC for purity and by mass spectrometry for identity.</p>
        <a class="btn btn--onDark btn--sm" href="/quality/">Read the process</a>
      </div>
    </div>
  </div>
  </nav>
</header>
<div class="nav-scrim" data-scrim data-open="false"></div>
<main id="main">
