'use strict';
/**
 * Sample catalogue data for the Purely Peptides design build.
 * Specifications are illustrative placeholders for layout purposes.
 * Replace with real ERP / WooCommerce data before launch.
 */

const brand = {
  name: 'Purely Peptides',
  short: 'Purely Peptides',
  legal: 'Purely Peptides LLC',
  tagline: 'Research materials, documented at the lot level.',
  email: 'support@purelypeptides.com',
  procurement: 'procurement@purelypeptides.com',
  phone: '+1 (617) 555-0148',
  address: ['84 Kendall Court, Suite 300', 'Cambridge, MA 02142', 'United States'],
  hours: 'Monday–Friday, 08:00–18:00 ET',
};

/* ---------------------------------------------------------------- taxonomy */

const categories = [
  {
    slug: 'research-peptides',
    name: 'Research Peptides',
    blurb: 'Lyophilised peptides supplied with lot-specific analytical documentation.',
  },
  {
    slug: 'protein-research',
    name: 'Protein Research',
    blurb: 'Fragments and analogues for structural and binding studies.',
  },
  {
    slug: 'metabolic-research',
    name: 'Metabolic Research',
    blurb: 'Materials used in energy substrate, adipose and mitochondrial models.',
  },
  {
    slug: 'cellular-research',
    name: 'Cellular Research',
    blurb: 'Compounds applied in repair, matrix and cell-signalling work.',
  },
  {
    slug: 'cognitive-research',
    name: 'Cognitive Research',
    blurb: 'Neuropeptides used in receptor and behavioural model studies.',
  },
  {
    slug: 'blends',
    name: 'Blends',
    blurb: 'Pre-combined formats prepared to a fixed ratio and documented as one lot.',
  },
];

const researchAreas = [
  'Metabolism',
  'Cell Signalling',
  'Cellular Repair',
  'Inflammatory Research',
  'Neuroscience',
  'Endocrine Research',
];

/* ---------------------------------------------------------------- products */

const products = [
  {
    sku: 'PP-1001', slug: 'bpc-157', name: 'BPC-157', category: 'research-peptides',
    area: 'Cellular Repair', cas: '137525-51-0',
    formula: 'C62H98N16O22', mw: '1419.53 g/mol',
    sequence: 'Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val',
    form: 'Lyophilised powder', purity: '99.4%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '5 mg', price: 46 }, { label: '10 mg', price: 78 }],
    stock: 'in-stock', featured: true, added: '2026-02-11',
    summary: 'A 15-amino-acid synthetic peptide derived from a sequence of human gastric juice protein BPC. Widely used as a reference material in tissue repair and gastrointestinal model research.',
    overview: 'BPC-157 is a synthetic pentadecapeptide corresponding to a partial sequence of body protection compound isolated from gastric juice. It is supplied as a lyophilised powder for in-vitro and preclinical laboratory research. Reported literature use includes models of angiogenesis, fibroblast migration and connective-tissue response. Purely Peptides supplies this material with RP-HPLC purity and mass-spectrometry identity data for the specific production lot.',
    lots: ['BP-260910', 'BP-260418', 'BP-251129'],
  },
  {
    sku: 'PP-1002', slug: 'tb-500', name: 'TB-500', category: 'research-peptides',
    area: 'Cellular Repair', cas: '885340-08-9',
    formula: 'C212H350N56O78S', mw: '4963.44 g/mol',
    sequence: 'Ac-Ser-Asp-Lys-Pro-Asp-Met-Ala-Glu-Ile-Glu-Lys-Phe-Asp-Lys-Ser-Lys-Leu-Lys-Lys-Thr-Glu-Thr-Gln-Glu-Lys-Asn-Pro-Leu-Pro-Ser-Lys-Glu-Thr-Ile-Glu-Gln-Glu-Lys-Gln-Ala-Gly-Glu-Ser',
    form: 'Lyophilised powder', purity: '99.1%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '2 mg', price: 52 }, { label: '5 mg', price: 112 }],
    stock: 'in-stock', featured: true, added: '2026-01-22',
    summary: 'Synthetic thymosin beta-4 analogue used in actin-binding and cell-migration research.',
    overview: 'TB-500 is a synthetic peptide corresponding to the active region of thymosin beta-4, a naturally occurring actin-sequestering protein. It is used in laboratory research examining actin polymerisation, cell migration and extracellular matrix interaction. Supplied lyophilised with lot-specific analytical documentation.',
    lots: ['TB-260722', 'TB-260215'],
  },
  {
    sku: 'PP-1003', slug: 'ghk-cu', name: 'GHK-Cu', category: 'cellular-research',
    area: 'Cellular Repair', cas: '89030-95-5',
    formula: 'C14H22CuN6O4', mw: '403.91 g/mol',
    sequence: 'Gly-His-Lys · Cu(II)',
    form: 'Lyophilised powder (blue)', purity: '99.6%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '50 mg', price: 38 }, { label: '100 mg', price: 64 }],
    stock: 'in-stock', featured: true, added: '2026-03-04',
    summary: 'Copper-binding tripeptide complex studied in matrix remodelling and gene-expression research.',
    overview: 'GHK-Cu is the copper(II) complex of the tripeptide glycyl-L-histidyl-L-lysine. The complex has been characterised extensively in the literature for its copper affinity and its use in matrix metalloproteinase and fibroblast gene-expression studies. Colour is a normal characteristic of the copper complex and is not an indicator of purity.',
    lots: ['GH-260803', 'GH-260119'],
  },
  {
    sku: 'PP-1004', slug: 'semax', name: 'Semax', category: 'cognitive-research',
    area: 'Neuroscience', cas: '80714-61-0',
    formula: 'C37H51N9O10S', mw: '813.93 g/mol',
    sequence: 'Met-Glu-His-Phe-Pro-Gly-Pro',
    form: 'Lyophilised powder', purity: '98.9%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '10 mg', price: 58 }, { label: '30 mg', price: 142 }],
    stock: 'in-stock', featured: true, added: '2025-11-30',
    summary: 'Synthetic ACTH(4-10) analogue used in neuropeptide and BDNF expression research.',
    overview: 'Semax is a synthetic heptapeptide analogue of the ACTH(4-10) fragment, extended with a Pro-Gly-Pro tail that increases enzymatic stability. It appears in neuroscience literature in studies of neurotrophic factor expression and receptor binding. Supplied as a lyophilised powder for laboratory research.',
    lots: ['SX-260605', 'SX-251208'],
  },
  {
    sku: 'PP-1005', slug: 'selank', name: 'Selank', category: 'cognitive-research',
    area: 'Neuroscience', cas: '129954-34-3',
    formula: 'C33H57N11O9', mw: '751.88 g/mol',
    sequence: 'Thr-Lys-Pro-Arg-Pro-Gly-Pro',
    form: 'Lyophilised powder', purity: '99.0%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '10 mg', price: 54 }, { label: '30 mg', price: 132 }],
    stock: 'in-stock', featured: false, added: '2025-12-14',
    summary: 'Tuftsin-derived heptapeptide used in GABAergic and immunomodulatory model research.',
    overview: 'Selank is a synthetic analogue of the endogenous immunomodulatory tetrapeptide tuftsin, extended with a Pro-Gly-Pro sequence. Published research covers GABA receptor interaction, monoamine turnover and cytokine expression in animal models.',
    lots: ['SL-260501'],
  },
  {
    sku: 'PP-1006', slug: 'epitalon', name: 'Epitalon', category: 'cellular-research',
    area: 'Cell Signalling', cas: '307297-39-8',
    formula: 'C14H22N4O9', mw: '390.35 g/mol',
    sequence: 'Ala-Glu-Asp-Gly',
    form: 'Lyophilised powder', purity: '99.3%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '10 mg', price: 44 }, { label: '50 mg', price: 148 }],
    stock: 'in-stock', featured: false, added: '2026-01-08',
    summary: 'Synthetic tetrapeptide studied in telomerase expression and pineal-regulation models.',
    overview: 'Epitalon is a synthetic tetrapeptide (Ala-Glu-Asp-Gly) derived from the pineal peptide preparation epithalamin. It appears in cell-culture literature examining telomerase activity and chromatin interaction. Supplied lyophilised for laboratory research.',
    lots: ['EP-260318'],
  },
  {
    sku: 'PP-1007', slug: 'ipamorelin', name: 'Ipamorelin', category: 'protein-research',
    area: 'Endocrine Research', cas: '170851-70-4',
    formula: 'C38H49N9O5', mw: '711.86 g/mol',
    sequence: 'Aib-His-D-2-Nal-D-Phe-Lys-NH2',
    form: 'Lyophilised powder', purity: '99.2%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '5 mg', price: 42 }, { label: '10 mg', price: 72 }],
    stock: 'low-stock', featured: true, added: '2026-02-27',
    summary: 'Selective ghrelin receptor (GHS-R1a) agonist pentapeptide used in receptor-binding studies.',
    overview: 'Ipamorelin is a synthetic pentapeptide characterised in the literature as a selective agonist at the growth hormone secretagogue receptor GHS-R1a. It is used as a reference ligand in receptor binding, selectivity and signalling assays.',
    lots: ['IP-260812', 'IP-260204'],
  },
  {
    sku: 'PP-1008', slug: 'cjc-1295', name: 'CJC-1295 (no DAC)', category: 'protein-research',
    area: 'Endocrine Research', cas: '863288-34-0',
    formula: 'C152H252N44O42', mw: '3367.90 g/mol',
    sequence: 'Tyr-D-Ala-Asp-Ala-Ile-Phe-Thr-Gln-Ser-Tyr-Arg-Lys-Val-Leu-Ala-Gln-Leu-Ser-Ala-Arg-Lys-Leu-Leu-Gln-Asp-Ile-Leu-Ser-Arg-NH2',
    form: 'Lyophilised powder', purity: '98.7%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '2 mg', price: 48 }, { label: '5 mg', price: 98 }],
    stock: 'in-stock', featured: false, added: '2025-10-19',
    summary: 'Modified GHRH(1-29) analogue used in receptor and peptide-stability research.',
    overview: 'CJC-1295 without drug affinity complex is a tetra-substituted analogue of GHRH(1-29). The substitutions are reported in the literature to reduce enzymatic degradation, making it a common reference material in peptide stability and GHRH receptor studies.',
    lots: ['CJ-260626'],
  },
  {
    sku: 'PP-1009', slug: 'kpv', name: 'KPV', category: 'cellular-research',
    area: 'Inflammatory Research', cas: '67727-97-3',
    formula: 'C16H29N5O4', mw: '355.43 g/mol',
    sequence: 'Lys-Pro-Val',
    form: 'Lyophilised powder', purity: '99.5%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '10 mg', price: 36 }, { label: '50 mg', price: 122 }],
    stock: 'in-stock', featured: false, added: '2026-03-19',
    summary: 'C-terminal α-MSH tripeptide used in cytokine and NF-κB pathway research.',
    overview: 'KPV is the C-terminal tripeptide fragment of alpha-melanocyte-stimulating hormone. Published cell-culture work examines its effect on NF-κB translocation and pro-inflammatory cytokine expression. Supplied lyophilised for laboratory research.',
    lots: ['KP-260904'],
  },
  {
    sku: 'PP-1010', slug: 'mots-c', name: 'MOTS-c', category: 'metabolic-research',
    area: 'Metabolism', cas: '1627580-64-6',
    formula: 'C101H152N28O22S2', mw: '2174.61 g/mol',
    sequence: 'Met-Arg-Trp-Gln-Glu-Met-Gly-Tyr-Ile-Phe-Tyr-Pro-Arg-Lys-Leu-Arg',
    form: 'Lyophilised powder', purity: '98.8%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '5 mg', price: 68 }, { label: '10 mg', price: 118 }],
    stock: 'in-stock', featured: true, added: '2026-04-02',
    summary: 'Mitochondrial-derived peptide used in AMPK signalling and metabolic model research.',
    overview: 'MOTS-c is a 16-amino-acid peptide encoded in the mitochondrial genome. It is described in the literature as a regulator of metabolic homeostasis acting through the AMPK pathway, and is used as a reference material in mitochondrial and metabolic signalling studies.',
    lots: ['MO-260728'],
  },
  {
    sku: 'PP-1011', slug: 'aod-9604', name: 'AOD-9604', category: 'metabolic-research',
    area: 'Metabolism', cas: '221231-10-3',
    formula: 'C78H123N23O23S2', mw: '1815.08 g/mol',
    sequence: 'Tyr-Leu-Arg-Ile-Val-Gln-Cys-Arg-Ser-Val-Glu-Gly-Ser-Cys-Gly-Phe',
    form: 'Lyophilised powder', purity: '98.6%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '2 mg', price: 56 }, { label: '5 mg', price: 118 }],
    stock: 'out-of-stock', featured: false, added: '2025-09-08',
    summary: 'C-terminal hGH fragment (176-191) analogue used in adipocyte model research.',
    overview: 'AOD-9604 is a modified fragment corresponding to residues 176-191 of human growth hormone, with an added tyrosine at the N-terminus. It appears in adipocyte lipolysis and metabolic model literature and is supplied here as a lyophilised research material.',
    lots: ['AO-251102'],
  },
  {
    sku: 'PP-1012', slug: 'thymosin-alpha-1', name: 'Thymosin α-1', category: 'protein-research',
    area: 'Inflammatory Research', cas: '62304-98-7',
    formula: 'C129H215N33O55', mw: '3108.29 g/mol',
    sequence: 'Ac-Ser-Asp-Ala-Ala-Val-Asp-Thr-Ser-Ser-Glu-Ile-Thr-Thr-Lys-Asp-Leu-Lys-Glu-Lys-Lys-Glu-Val-Val-Glu-Glu-Ala-Glu-Asn',
    form: 'Lyophilised powder', purity: '99.0%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '5 mg', price: 74 }, { label: '10 mg', price: 132 }],
    stock: 'in-stock', featured: false, added: '2026-02-05',
    summary: '28-residue thymic peptide used in immune-signalling and T-cell model research.',
    overview: 'Thymosin alpha-1 is a 28-amino-acid acetylated peptide originally isolated from thymosin fraction 5. It is used in immunology research examining T-cell maturation markers, toll-like receptor signalling and cytokine profiles.',
    lots: ['TA-260411'],
  },
  {
    sku: 'PP-1013', slug: 'pt-141', name: 'PT-141', category: 'research-peptides',
    area: 'Neuroscience', cas: '189691-06-3',
    formula: 'C50H68N14O10', mw: '1025.16 g/mol',
    sequence: 'Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-OH',
    form: 'Lyophilised powder', purity: '98.9%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '10 mg', price: 62 }, { label: '20 mg', price: 108 }],
    stock: 'in-stock', featured: false, added: '2026-01-15',
    summary: 'Cyclic melanocortin receptor agonist used in MC1R/MC4R binding studies.',
    overview: 'PT-141 is a cyclic heptapeptide analogue of alpha-MSH and a characterised agonist at melanocortin receptors. It is used as a reference ligand in receptor selectivity and binding assays.',
    lots: ['PT-260530'],
  },
  {
    sku: 'PP-1014', slug: 'tesamorelin', name: 'Tesamorelin', category: 'metabolic-research',
    area: 'Endocrine Research', cas: '218949-48-5',
    formula: 'C221H366N72O67S', mw: '5135.90 g/mol',
    sequence: 'trans-3-hexenoyl-GHRH(1-44)-NH2',
    form: 'Lyophilised powder', purity: '98.5%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '2 mg', price: 96 }, { label: '5 mg', price: 210 }],
    stock: 'low-stock', featured: false, added: '2025-11-11',
    summary: 'Stabilised GHRH(1-44) analogue used in endocrine receptor research.',
    overview: 'Tesamorelin is a synthetic analogue of human growth hormone releasing hormone (1-44) carrying an N-terminal trans-3-hexenoyl group. It is used in laboratory research on GHRH receptor binding and peptide stability.',
    lots: ['TS-260209'],
  },
  {
    sku: 'PP-1015', slug: 'glutathione', name: 'Glutathione (reduced)', category: 'cellular-research',
    area: 'Cell Signalling', cas: '70-18-8',
    formula: 'C10H17N3O6S', mw: '307.32 g/mol',
    sequence: 'γ-Glu-Cys-Gly',
    form: 'Lyophilised powder', purity: '99.7%', method: 'RP-HPLC / Titration',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '100 mg', price: 32 }, { label: '500 mg', price: 96 }],
    stock: 'in-stock', featured: false, added: '2026-03-27',
    summary: 'Reduced tripeptide thiol used as a redox reference standard.',
    overview: 'Reduced glutathione is the principal intracellular thiol antioxidant and a standard reference material in redox biology. Supplied as a lyophilised powder with assay and purity data for the production lot.',
    lots: ['GS-260901'],
  },
  {
    sku: 'PP-2001', slug: 'repair-blend-r2', name: 'Repair Blend R-2', category: 'blends',
    area: 'Cellular Repair', cas: 'Mixture - see components',
    formula: 'Mixture', mw: 'Not applicable (mixture)',
    sequence: 'BPC-157 + TB-500, 1:1 by mass',
    form: 'Lyophilised powder', purity: 'Components ≥ 98.5%', method: 'RP-HPLC (per component)',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '10 mg', price: 118 }],
    stock: 'in-stock', featured: false, added: '2026-04-18',
    summary: 'Fixed-ratio combination of BPC-157 and TB-500, documented as a single production lot.',
    overview: 'Repair Blend R-2 combines BPC-157 and TB-500 at a 1:1 mass ratio in a single vial. Each blend lot carries chromatographic data for both components, allowing the ratio to be confirmed before use. Supplied for laboratory research only.',
    lots: ['RB-260815'],
  },
  {
    sku: 'PP-2002', slug: 'metabolic-blend-m1', name: 'Metabolic Blend M-1', category: 'blends',
    area: 'Metabolism', cas: 'Mixture - see components',
    formula: 'Mixture', mw: 'Not applicable (mixture)',
    sequence: 'MOTS-c + AOD-9604, 2:1 by mass',
    form: 'Lyophilised powder', purity: 'Components ≥ 98.5%', method: 'RP-HPLC (per component)',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '10 mg', price: 138 }],
    stock: 'in-stock', featured: false, added: '2026-04-18',
    summary: 'Fixed-ratio combination of MOTS-c and AOD-9604 for metabolic model work.',
    overview: 'Metabolic Blend M-1 combines MOTS-c and AOD-9604 at a 2:1 mass ratio. Blend lots are documented with chromatographic data for each component so the ratio can be verified prior to use.',
    lots: ['MB-260820'],
  },
  {
    sku: 'PP-1016', slug: 'hexarelin', name: 'Hexarelin', category: 'protein-research',
    area: 'Endocrine Research', cas: '140703-51-1',
    formula: 'C47H58N12O6', mw: '887.03 g/mol',
    sequence: 'His-D-2-methyl-Trp-Ala-Trp-D-Phe-Lys-NH2',
    form: 'Lyophilised powder', purity: '98.8%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '2 mg', price: 44 }, { label: '5 mg', price: 88 }],
    stock: 'in-stock', featured: false, added: '2025-12-02',
    summary: 'Synthetic hexapeptide GHS-R agonist used in receptor pharmacology research.',
    overview: 'Hexarelin is a synthetic hexapeptide growth hormone secretagogue used as a reference agonist in GHS-R1a and CD36 receptor studies.',
    lots: ['HX-260107'],
  },
  {
    sku: 'PP-1017', slug: 'sermorelin', name: 'Sermorelin', category: 'metabolic-research',
    area: 'Endocrine Research', cas: '86168-78-7',
    formula: 'C149H246N44O42S', mw: '3357.88 g/mol',
    sequence: 'GHRH(1-29)-NH2',
    form: 'Lyophilised powder', purity: '98.7%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '2 mg', price: 46 }, { label: '5 mg', price: 92 }],
    stock: 'in-stock', featured: false, added: '2026-02-19',
    summary: 'GHRH(1-29) amide, the minimum fully active GHRH fragment.',
    overview: 'Sermorelin is the amidated 1-29 fragment of growth hormone releasing hormone, described in the literature as the shortest fully active GHRH sequence. Used as a reference peptide in receptor and stability research.',
    lots: ['SR-260322'],
  },
  {
    sku: 'PP-1018', slug: 'll-37', name: 'LL-37', category: 'cellular-research',
    area: 'Inflammatory Research', cas: '154947-66-7',
    formula: 'C205H340N60O53', mw: '4493.28 g/mol',
    sequence: 'Leu-Leu-Gly-Asp-Phe-Phe-Arg-Lys-Ser-Lys-Glu-Lys-Ile-Gly-Lys-Glu-Phe-Lys-Arg-Ile-Val-Gln-Arg-Ile-Lys-Asp-Phe-Leu-Arg-Asn-Leu-Val-Pro-Arg-Thr-Glu-Ser',
    form: 'Lyophilised powder', purity: '98.5%', method: 'RP-HPLC / MS',
    storage: '−20 °C, desiccated, protected from light',
    sizes: [{ label: '1 mg', price: 88 }, { label: '5 mg', price: 340 }],
    stock: 'in-stock', featured: false, added: '2026-03-11',
    summary: 'Human cathelicidin-derived antimicrobial peptide used in innate-immunity research.',
    overview: 'LL-37 is the 37-residue C-terminal peptide of human cathelicidin hCAP18. It is a widely cited reference material in antimicrobial peptide, membrane interaction and innate immune signalling research.',
    lots: ['LL-260614'],
  },
];

/* -------------------------------------------------------------------- lots */

const lots = [
  { lot: 'BP-260910', product: 'BPC-157', slug: 'bpc-157', date: '10 Sep 2026', purity: '99.4%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '10 mg' },
  { lot: 'BP-260418', product: 'BPC-157', slug: 'bpc-157', date: '18 Apr 2026', purity: '99.1%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '5 mg' },
  { lot: 'BP-251129', product: 'BPC-157', slug: 'bpc-157', date: '29 Nov 2025', purity: '98.9%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'archived', size: '5 mg' },
  { lot: 'TB-260722', product: 'TB-500', slug: 'tb-500', date: '22 Jul 2026', purity: '99.1%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '5 mg' },
  { lot: 'TB-260215', product: 'TB-500', slug: 'tb-500', date: '15 Feb 2026', purity: '98.8%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'archived', size: '2 mg' },
  { lot: 'GH-260803', product: 'GHK-Cu', slug: 'ghk-cu', date: '03 Aug 2026', purity: '99.6%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '100 mg' },
  { lot: 'GH-260119', product: 'GHK-Cu', slug: 'ghk-cu', date: '19 Jan 2026', purity: '99.4%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'archived', size: '50 mg' },
  { lot: 'SX-260605', product: 'Semax', slug: 'semax', date: '05 Jun 2026', purity: '98.9%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '10 mg' },
  { lot: 'SX-251208', product: 'Semax', slug: 'semax', date: '08 Dec 2025', purity: '98.7%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'archived', size: '10 mg' },
  { lot: 'SL-260501', product: 'Selank', slug: 'selank', date: '01 May 2026', purity: '99.0%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '10 mg' },
  { lot: 'EP-260318', product: 'Epitalon', slug: 'epitalon', date: '18 Mar 2026', purity: '99.3%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '50 mg' },
  { lot: 'IP-260812', product: 'Ipamorelin', slug: 'ipamorelin', date: '12 Aug 2026', purity: '99.2%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '10 mg' },
  { lot: 'IP-260204', product: 'Ipamorelin', slug: 'ipamorelin', date: '04 Feb 2026', purity: '99.0%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'archived', size: '5 mg' },
  { lot: 'CJ-260626', product: 'CJC-1295 (no DAC)', slug: 'cjc-1295', date: '26 Jun 2026', purity: '98.7%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '5 mg' },
  { lot: 'KP-260904', product: 'KPV', slug: 'kpv', date: '04 Sep 2026', purity: '99.5%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '50 mg' },
  { lot: 'MO-260728', product: 'MOTS-c', slug: 'mots-c', date: '28 Jul 2026', purity: '98.8%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '10 mg' },
  { lot: 'AO-251102', product: 'AOD-9604', slug: 'aod-9604', date: '02 Nov 2025', purity: '98.6%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'archived', size: '5 mg' },
  { lot: 'TA-260411', product: 'Thymosin α-1', slug: 'thymosin-alpha-1', date: '11 Apr 2026', purity: '99.0%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '10 mg' },
  { lot: 'PT-260530', product: 'PT-141', slug: 'pt-141', date: '30 May 2026', purity: '98.9%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '20 mg' },
  { lot: 'TS-260209', product: 'Tesamorelin', slug: 'tesamorelin', date: '09 Feb 2026', purity: '98.5%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '5 mg' },
  { lot: 'GS-260901', product: 'Glutathione (reduced)', slug: 'glutathione', date: '01 Sep 2026', purity: '99.7%', method: 'RP-HPLC', identity: 'Conforms - Titration', lab: 'Janoshik Analytical', status: 'available', size: '500 mg' },
  { lot: 'RB-260815', product: 'Repair Blend R-2', slug: 'repair-blend-r2', date: '15 Aug 2026', purity: '98.9% / 99.0%', method: 'RP-HPLC', identity: 'Conforms - MS (both components)', lab: 'Janoshik Analytical', status: 'available', size: '10 mg' },
  { lot: 'MB-260820', product: 'Metabolic Blend M-1', slug: 'metabolic-blend-m1', date: '20 Aug 2026', purity: '98.8% / 98.6%', method: 'RP-HPLC', identity: 'Conforms - MS (both components)', lab: 'Janoshik Analytical', status: 'available', size: '10 mg' },
  { lot: 'HX-260107', product: 'Hexarelin', slug: 'hexarelin', date: '07 Jan 2026', purity: '98.8%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '5 mg' },
  { lot: 'SR-260322', product: 'Sermorelin', slug: 'sermorelin', date: '22 Mar 2026', purity: '98.7%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '5 mg' },
  { lot: 'LL-260614', product: 'LL-37', slug: 'll-37', date: '14 Jun 2026', purity: '98.5%', method: 'RP-HPLC', identity: 'Conforms - MS', lab: 'Janoshik Analytical', status: 'available', size: '1 mg' },
];

/* ---------------------------------------------------------------- articles */

const articles = [
  {
    slug: 'reading-an-hplc-purity-result',
    title: 'How to read an HPLC purity result',
    category: 'Methods',
    date: '2026-08-14',
    dateLabel: '14 August 2026',
    readTime: '9 min',
    author: 'Dr. Ines Karlsson',
    role: 'Head of Analytical Services',
    excerpt: 'A purity figure is a summary of a chromatogram, not a substitute for it. What the integration actually measures, and where the number can mislead.',
    abstract: 'Reversed-phase HPLC is the default purity method for synthetic peptides, and a single percentage is the number most often quoted from it. That percentage is an area-normalised ratio derived from a specific detection wavelength, gradient and column. This article explains how the figure is produced, which impurities it can and cannot see, and what to check on the chromatogram before accepting the number at face value.',
    tags: ['HPLC', 'Purity', 'Analytical'],
    featured: true,
  },
  {
    slug: 'what-a-certificate-of-analysis-contains',
    title: 'What a certificate of analysis actually contains',
    category: 'Quality',
    date: '2026-07-29',
    dateLabel: '29 July 2026',
    readTime: '7 min',
    author: 'Marcus Oyelaran',
    role: 'Quality Systems Manager',
    excerpt: 'Certificates vary widely between suppliers. The fields that carry real information, and the ones that carry none.',
    abstract: 'A certificate of analysis is a record of what was tested, by whom, when, and against which specification. Documents that omit any of those four elements are difficult to use. This article walks through each field of a peptide COA and explains how to evaluate one you have been sent.',
    tags: ['COA', 'Documentation', 'Quality'],
    featured: true,
  },
  {
    slug: 'storage-and-reconstitution-of-lyophilised-peptides',
    title: 'Storage and reconstitution of lyophilised peptides',
    category: 'Storage',
    date: '2026-06-30',
    dateLabel: '30 June 2026',
    readTime: '11 min',
    author: 'Dr. Ines Karlsson',
    role: 'Head of Analytical Services',
    excerpt: 'Temperature, moisture and freeze-thaw cycles account for most avoidable loss of peptide integrity in the laboratory.',
    abstract: 'Lyophilised peptides are stable for extended periods when stored correctly, and degrade quickly when they are not. This article summarises the physical mechanisms behind peptide degradation in storage and the handling practices that address each one.',
    tags: ['Storage', 'Handling', 'Stability'],
    featured: true,
  },
  {
    slug: 'mass-spectrometry-as-an-identity-check',
    title: 'Mass spectrometry as an identity check',
    category: 'Methods',
    date: '2026-05-21',
    dateLabel: '21 May 2026',
    readTime: '8 min',
    author: 'Dr. Peter Nwosu',
    role: 'Analytical Chemist',
    excerpt: 'HPLC tells you how much of one thing is present. MS tells you whether that thing is what the label says.',
    abstract: 'Purity and identity are separate questions requiring separate methods. This article explains why an HPLC result alone cannot confirm identity, and how ESI-MS data on a certificate should be interpreted.',
    tags: ['Mass spectrometry', 'Identity', 'Analytical'],
    featured: false,
  },
  {
    slug: 'lot-traceability-in-research-procurement',
    title: 'Lot traceability in research procurement',
    category: 'Industry',
    date: '2026-04-16',
    dateLabel: '16 April 2026',
    readTime: '6 min',
    author: 'Marcus Oyelaran',
    role: 'Quality Systems Manager',
    excerpt: 'Reproducibility problems are often supply problems. Recording lot numbers alongside experimental data closes a common gap.',
    abstract: 'When an experiment fails to reproduce, the material is rarely the first suspect and often should be. This article makes the case for treating lot numbers as experimental metadata and outlines a minimal record-keeping practice.',
    tags: ['Traceability', 'Reproducibility', 'Procurement'],
    featured: false,
  },
  {
    slug: 'peptide-solubility-a-practical-guide',
    title: 'Peptide solubility: a practical guide',
    category: 'Product Guides',
    date: '2026-03-05',
    dateLabel: '5 March 2026',
    readTime: '10 min',
    author: 'Dr. Peter Nwosu',
    role: 'Analytical Chemist',
    excerpt: 'Sequence charge and hydrophobicity predict most solubility behaviour. A short decision path for choosing a solvent.',
    abstract: 'Difficulty dissolving a peptide is usually predictable from its sequence. This guide sets out a decision path based on net charge and hydrophobic residue content, and covers the common solvents and their trade-offs.',
    tags: ['Solubility', 'Handling', 'Guide'],
    featured: false,
  },
  {
    slug: 'endotoxin-testing-when-it-matters',
    title: 'Endotoxin testing: when it matters',
    category: 'Quality',
    date: '2026-02-12',
    dateLabel: '12 February 2026',
    readTime: '7 min',
    author: 'Dr. Ines Karlsson',
    role: 'Head of Analytical Services',
    excerpt: 'Endotoxin limits are irrelevant to some assays and decisive in others. How to tell which situation you are in.',
    abstract: 'Bacterial endotoxin contamination can confound cell-based assays at concentrations far below those that matter elsewhere. This article covers the LAL method, typical limits and the experimental contexts in which endotoxin data should be requested.',
    tags: ['Endotoxin', 'Cell culture', 'Quality'],
    featured: false,
  },
  {
    slug: 'comparing-synthesis-routes-for-short-peptides',
    title: 'Comparing synthesis routes for short peptides',
    category: 'Research',
    date: '2026-01-23',
    dateLabel: '23 January 2026',
    readTime: '12 min',
    author: 'Dr. Peter Nwosu',
    role: 'Analytical Chemist',
    excerpt: 'Solid-phase and solution-phase synthesis leave different impurity signatures. Reading the route from the chromatogram.',
    abstract: 'The impurity profile of a synthetic peptide carries information about how it was made. This article compares Fmoc solid-phase synthesis with solution-phase approaches and describes the characteristic by-products of each.',
    tags: ['Synthesis', 'SPPS', 'Impurities'],
    featured: false,
  },
];

// Counts are derived, never hand-maintained: the nav, filters and category
// panels must always agree with the catalogue itself.
categories.forEach((c) => {
  c.count = products.filter((p) => p.category === c.slug).length;
});

module.exports = { brand, categories, researchAreas, products, lots, articles };
